# Generated by Django 5.0.6 on 2024-05-24 19:31

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.upload_book_cover),
        ),
    ]
